import os
from dotenv import load_dotenv

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o")
OPENAI_COPILOT_MODEL = os.getenv("OPENAI_COPILOT_MODEL", "gpt-4o")
OPENAI_WORKER_MODEL = os.getenv("OPENAI_WORKER_MODEL", "gpt-4o-mini")

# Azure AI Foundry (opsiyonel - deploy icin)
FOUNDRY_PROJECT_ENDPOINT = os.getenv("FOUNDRY_PROJECT_ENDPOINT", "")
FOUNDRY_RESPONSES_ENDPOINT = os.getenv("FOUNDRY_RESPONSES_ENDPOINT", "")
FOUNDRY_ACTIVITY_ENDPOINT = os.getenv("FOUNDRY_ACTIVITY_ENDPOINT", "")
FOUNDRY_ACCOUNT_NAME = os.getenv("FOUNDRY_ACCOUNT_NAME", "")
FOUNDRY_PROJECT_NAME = os.getenv("FOUNDRY_PROJECT_NAME", "")
FOUNDRY_APPLICATION_NAME = os.getenv("FOUNDRY_APPLICATION_NAME", "")
FOUNDRY_AGENT_DEPLOYMENT_NAME = os.getenv("FOUNDRY_AGENT_DEPLOYMENT_NAME", "")
FOUNDRY_AGENT_DEPLOYMENT_TYPE = os.getenv("FOUNDRY_AGENT_DEPLOYMENT_TYPE", "Managed")
FOUNDRY_AGENT_MODEL = os.getenv("FOUNDRY_AGENT_MODEL", "")
FOUNDRY_WORKFLOW_AGENT_NAME = os.getenv("FOUNDRY_WORKFLOW_AGENT_NAME", "")
FOUNDRY_MANAGEMENT_API_VERSION = os.getenv("FOUNDRY_MANAGEMENT_API_VERSION", "2025-10-01-preview")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4o-mini")
AZURE_SUBSCRIPTION_ID = os.getenv("AZURE_SUBSCRIPTION_ID", "")
AZURE_RESOURCE_GROUP = os.getenv("AZURE_RESOURCE_GROUP", "")
